## Importing libraries

In [1]:
import pandas as pd # create, manipulate csv files
import numpy as np # doing mathematical operations 
import matplotlib.pyplot as plt

## create dataframe from dict (Just for exemple )


In [2]:
people_dict = { "weight": pd.Series([68, 83, 112],index=["alice", "bob", "charles"]),   "birthyear": pd.Series([1984, 1985, 1992], index=["bob", "alice", "charles"], name="year"),
"children": pd.Series([0, 3], index=["charles", "bob"]),
"hobby": pd.Series(["Biking", "Dancing"], index=["alice", "bob"]),}

In [4]:
people = pd.DataFrame(people_dict)

## Reading data 

In [5]:
data=pd.read_csv('house_prices.csv')

## Investigating the data

In [11]:
data.head()

Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0     1  114300  1790         2          2       2    No         East
1     2  114200  2030         4          2       3    No         East
2     3  114800  1740         3          2       1    No         East
3     4   94700  1980         3          2       3    No         East
4     5  119800  2130         3          3       3    No         East

#### head(): returns the top 5 rows in the dataframe object
#### tail(): returns the bottom 5 rows in the dataframe
#### info(): prints the summary of the dataframe
#### describe(): gives a nice overview of the main aggregated values over each column

In [10]:
data.dtypes

Home             int64
Price            int64
SqFt             int64
Bedrooms         int64
Bathrooms        int64
Offers           int64
Brick           object
Neighborhood    object
dtype: object

In [34]:
data.shape

(128, 8)

In [12]:
data.isnull().sum()

Home            0
Price           0
SqFt            0
Bedrooms        0
Bathrooms       0
Offers          0
Brick           7
Neighborhood    0
dtype: int64

In [17]:
data=data.dropna()# guess the result ? how many rows in data now ? 

In [15]:
data.dropna(inplace=True)

In [16]:
data.shape

(121, 8)

## Prepare our data

In [18]:
def transform(x):
    if ( x=='No'):
        return 0
    return 1

In [19]:
data['Brick']=data['Brick'].apply(lambda x : transform(x))

In [20]:
data.head()

Home   Price  SqFt  Bedrooms  Bathrooms  Offers  Brick Neighborhood
0     1  114300  1790         2          2       2      0         East
1     2  114200  2030         4          2       3      0         East
2     3  114800  1740         3          2       1      0         East
3     4   94700  1980         3          2       3      0         East
4     5  119800  2130         3          3       3      0         East

In [21]:
data.drop(columns=['Neighborhood','Home','Offers'],inplace=True)

In [22]:
data.head()

Price  SqFt  Bedrooms  Bathrooms  Brick
0  114300  1790         2          2      0
1  114200  2030         4          2      0
2  114800  1740         3          2      0
3   94700  1980         3          2      0
4  119800  2130         3          3      0

In [23]:
data.shape

(121, 5)

In [25]:
train_data=data[:100]

test_data=data[100:]


In [27]:
%%time 
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(train_data.drop(columns=['Price']).values, train_data['Price'].values).predict(test_data.drop(columns=['Price']).values)

CPU times: user 21.3 ms, sys: 380 µs, total: 21.7 ms
Wall time: 22 ms


In [73]:
y_pred

array([129800, 125700, 147700, 125700, 102600, 125700, 121300, 125700,
       125700, 142600, 125700, 125700, 125700, 129800, 129800, 125700,
       129800, 127700, 125700, 125700, 129800, 129800, 125700])

In [28]:
test_data['Price'].values

array([136800, 211200,  82300, 146900, 108500, 134000, 117000, 108700,
       111600, 114900, 115700, 124500, 102500, 150200, 110400, 105600,
       119700, 147900, 113500, 149900, 124600])

In [76]:
accuracy_score(test_data['Price'].values, y_pred)

0.0

In [63]:
# shit ! wrong algorithme choosed  reason ?

In [29]:
gnb = GaussianNB()
y_pred = gnb.fit(train_data.drop(columns=['Bathrooms']).values, train_data['Bathrooms'].values).predict(test_data.drop(columns=['Bathrooms']).values)

In [30]:
y_pred

array([3, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 3, 3])

In [31]:
test_data['Bathrooms'].values

array([3, 3, 2, 3, 2, 2, 3, 2, 2, 2, 2, 3, 3, 2, 3, 3, 3, 3, 2, 3, 3])

In [32]:
accuracy_score(test_data['Bathrooms'].values, y_pred)

NameError: name 'accuracy_score' is not defined

### Cross validation ??

In [33]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(gnb, train_data.drop(columns=['Bathrooms']).values, train_data['Bathrooms'].values, cv=5)
scores                      

array([0.76190476, 0.85714286, 0.7       , 0.84210526, 0.68421053])

In [34]:
scores.mean()

0.7690726817042606

In [35]:
#avant gout deep learning if there is time remaining 

### more exemples here _

In [50]:
'''https://cloudxlab.com/blog/numpy-pandas-introduction/'''

'https://cloudxlab.com/blog/numpy-pandas-introduction/'

In [81]:
## Final Exemple , whats the problem, what data we need 

In [82]:
'https://www.exchange-rates.org/history/TND/USD/T'

'https://www.exchange-rates.org/history/TND/USD/T'

In [ ]:
#chbiha l header haka ? 